/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumTaskStatus } from "./EnumTaskStatus";
import { ChecklistListRelationFilter } from "../../checklist/base/ChecklistListRelationFilter";
import { AgentWhereUniqueInput } from "../../agent/base/AgentWhereUniqueInput";
import { AdministratorWhereUniqueInput } from "../../administrator/base/AdministratorWhereUniqueInput";

@InputType()
class TaskWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumTaskStatus,
  })
  @IsEnum(EnumTaskStatus)
  @IsOptional()
  @Field(() => EnumTaskStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: () => ChecklistListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ChecklistListRelationFilter)
  @IsOptional()
  @Field(() => ChecklistListRelationFilter, {
    nullable: true,
  })
  checklists?: ChecklistListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AgentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AgentWhereUniqueInput)
  @IsOptional()
  @Field(() => AgentWhereUniqueInput, {
    nullable: true,
  })
  agent?: AgentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AdministratorWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdministratorWhereUniqueInput)
  @IsOptional()
  @Field(() => AdministratorWhereUniqueInput, {
    nullable: true,
  })
  administrator?: AdministratorWhereUniqueInput;
}

export { TaskWhereInput as TaskWhereInput };
