/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TaskService } from "../task.service";
import { TaskCreateInput } from "./TaskCreateInput";
import { Task } from "./Task";
import { TaskFindManyArgs } from "./TaskFindManyArgs";
import { TaskWhereUniqueInput } from "./TaskWhereUniqueInput";
import { TaskUpdateInput } from "./TaskUpdateInput";
import { ChecklistFindManyArgs } from "../../checklist/base/ChecklistFindManyArgs";
import { Checklist } from "../../checklist/base/Checklist";
import { ChecklistWhereUniqueInput } from "../../checklist/base/ChecklistWhereUniqueInput";

export class TaskControllerBase {
  constructor(protected readonly service: TaskService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Task })
  async createTask(@common.Body() data: TaskCreateInput): Promise<Task> {
    return await this.service.createTask({
      data: {
        ...data,

        agent: data.agent
          ? {
              connect: data.agent,
            }
          : undefined,

        administrator: data.administrator
          ? {
              connect: data.administrator,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,

        agent: {
          select: {
            id: true,
          },
        },

        administrator: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Task] })
  @ApiNestedQuery(TaskFindManyArgs)
  async tasks(@common.Req() request: Request): Promise<Task[]> {
    const args = plainToClass(TaskFindManyArgs, request.query);
    return this.service.tasks({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,

        agent: {
          select: {
            id: true,
          },
        },

        administrator: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Task })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async task(
    @common.Param() params: TaskWhereUniqueInput
  ): Promise<Task | null> {
    const result = await this.service.task({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,

        agent: {
          select: {
            id: true,
          },
        },

        administrator: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Task })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTask(
    @common.Param() params: TaskWhereUniqueInput,
    @common.Body() data: TaskUpdateInput
  ): Promise<Task | null> {
    try {
      return await this.service.updateTask({
        where: params,
        data: {
          ...data,

          agent: data.agent
            ? {
                connect: data.agent,
              }
            : undefined,

          administrator: data.administrator
            ? {
                connect: data.administrator,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          status: true,

          agent: {
            select: {
              id: true,
            },
          },

          administrator: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Task })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTask(
    @common.Param() params: TaskWhereUniqueInput
  ): Promise<Task | null> {
    try {
      return await this.service.deleteTask({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          status: true,

          agent: {
            select: {
              id: true,
            },
          },

          administrator: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/checklists")
  @ApiNestedQuery(ChecklistFindManyArgs)
  async findChecklists(
    @common.Req() request: Request,
    @common.Param() params: TaskWhereUniqueInput
  ): Promise<Checklist[]> {
    const query = plainToClass(ChecklistFindManyArgs, request.query);
    const results = await this.service.findChecklists(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        taskItem: true,
        completed: true,

        task: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/checklists")
  async connectChecklists(
    @common.Param() params: TaskWhereUniqueInput,
    @common.Body() body: ChecklistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      checklists: {
        connect: body,
      },
    };
    await this.service.updateTask({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/checklists")
  async updateChecklists(
    @common.Param() params: TaskWhereUniqueInput,
    @common.Body() body: ChecklistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      checklists: {
        set: body,
      },
    };
    await this.service.updateTask({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/checklists")
  async disconnectChecklists(
    @common.Param() params: TaskWhereUniqueInput,
    @common.Body() body: ChecklistWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      checklists: {
        disconnect: body,
      },
    };
    await this.service.updateTask({
      where: params,
      data,
      select: { id: true },
    });
  }
}
